[comment]: # (README.md is autogenerated from src/lib.rs by `cargo readme > README.md`)

# !!! main branch is ureq 3.x !!!

In anticipation of releasig ureq 3.x, the main branch is now the 3.x version. The current
main released version is in the [2.x](https://github.com/algesten/ureq/tree/2.x) branch.

---

# {{crate}}

{{readme}}
